### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by ruettenm**
Hi,

this time I am contributing to your project (after my team colleagues @robaca and @jverhoelen).
We are using your library already since a few years.

We would like to update the cassandra-driver because the DataStax Cassandra Driver v2/v3 drivers are deprecated and out of support end of 2021.

I did also some other changes:
* I removed mocha because the project do not have unit tests and the used version has vulnerabilities. Also an update to mocha 9 was not so easy :)
* I updated the ne latest LTS version (16)
* I removed the `package-lock.json` from the .gitignore (It's best practice to commit it)
* I also updated the other dependencies to the latest versions.
* I did a version bump to v3 because it's now required to provide a "localDataCenter" in the cassandra configuration

Best regards
Matthias

### CODE REVIEW

**Comment by ruettenm** [comment]
@joeledwards I you like I could also take over the maintenance of the project.

**Comment by joeledwards** [comment]
@ruettenm , I am happy to hand over maintenance of the project to you. Let me review the process for transferring ownership of the npm package.

**Comment by joeledwards** [comment]
@ruettenm , what is your user name on npmjs.com?

**Comment by joeledwards** [comment]
I located your npm user through your jira-activity package. I have added you as a maintainer.

**Comment by ruettenm** [comment]
Thanks! Would it be okay for you if I migrate the project to TypeScript? I not really familiar with coffee script ;-)

**Comment by joeledwards** [comment]
@ruettenm I think porting to TypeScript is a great idea!

Feel free to ping me in a PR when it is ready (if you want a review). But feel free to publish when you are ready now that you are a maintainer.

Also, I recommend updating the project links to your github repo so the package reflects the most recent changes.

**Pull request closed without merging**
